// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9n9KuBXWJhNFZENvFAk-A2ATPHkUL6E0',
    appId: '1:32888732075:web:8c331e59c0c1ee6161faee',
    messagingSenderId: '32888732075',
    projectId: 'quiz-demo-8701e',
    authDomain: 'quiz-demo-8701e.firebaseapp.com',
    storageBucket: 'quiz-demo-8701e.appspot.com',
    measurementId: 'G-1JEXXKW8HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWG4gaJFlD0fD7fWjz0uRAfamk8_JLchQ',
    appId: '1:32888732075:android:9875948d7520c91061faee',
    messagingSenderId: '32888732075',
    projectId: 'quiz-demo-8701e',
    storageBucket: 'quiz-demo-8701e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbxzkL5pBAOR_-G6whDjH0ULrhMtcli_8',
    appId: '1:32888732075:ios:8cae91152105d26361faee',
    messagingSenderId: '32888732075',
    projectId: 'quiz-demo-8701e',
    storageBucket: 'quiz-demo-8701e.appspot.com',
    iosBundleId: 'com.example.quizDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbxzkL5pBAOR_-G6whDjH0ULrhMtcli_8',
    appId: '1:32888732075:ios:8cae91152105d26361faee',
    messagingSenderId: '32888732075',
    projectId: 'quiz-demo-8701e',
    storageBucket: 'quiz-demo-8701e.appspot.com',
    iosBundleId: 'com.example.quizDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9n9KuBXWJhNFZENvFAk-A2ATPHkUL6E0',
    appId: '1:32888732075:web:ce2813af133428d961faee',
    messagingSenderId: '32888732075',
    projectId: 'quiz-demo-8701e',
    authDomain: 'quiz-demo-8701e.firebaseapp.com',
    storageBucket: 'quiz-demo-8701e.appspot.com',
    measurementId: 'G-7WXHKY2RHV',
  );
}
